spring:
  datasource:
    url: jdbc:mysql://47.100.5.130:3306/schema?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 20

server:
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /api
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.example.mall: debug


